/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package israa;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import rey.HotelGUI;
 

/**
 *
 * @author Israa
 */
public class BookingUI extends javax.swing.JFrame {

    /**
     * Creates new form BookingUI
     */
    public BookingUI() {
        initComponents();
        try {
            //Loading the jdbc driver
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            //Get a connection to database
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/" + dbName, userName, password);
        } catch (Exception e) {
            System.err.println("DATABASE CONNECTION ERROR: " + e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Next = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Next.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Next.setText("Next");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(102, 0, 102));
        jCheckBox1.setText("Airline Reservation");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(102, 0, 102));
        jCheckBox2.setText("Hotel Reservation");

        jCheckBox3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(102, 0, 102));
        jCheckBox3.setText("Tour Reservation");

        jCheckBox4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(102, 0, 102));
        jCheckBox4.setText("Car rental");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Booking Info:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Next, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox3)
                                    .addComponent(jCheckBox2)
                                    .addComponent(jCheckBox1)
                                    .addComponent(jCheckBox4))
                                .addGap(213, 213, 213))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel1)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox2)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox3)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox4)
                .addGap(38, 38, 38)
                .addComponent(Next, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private int custID;
private Connection con;
   private final String userName = "root";
    private final String password = "";
    private final String dbName = "travel_agency";
Booking b= new Booking();
    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
       if(jCheckBox1.isSelected())
        {
               ArilineGUI a = new ArilineGUI();
                  a.setVisible(true);
        }
       else if(jCheckBox2.isSelected())
        {
            HotelGUI add = new HotelGUI();
            add.setVisible(true);
        }

//        else if (jCheckBox3.isSelected())
////        {
//            tour h= new tour();
//            h.setVisible(true);
//           }
//          else if(jCheckBox4.isSelected())
////       {
////            car h= new car();
//            h.setVisible(true);
//           }


       
        
//    int custID = Integer.parseInt(jTextField1.getText());
//    if(custID!=0)
//  {
//          try {
//            Statement stmt = con.createStatement();
//            ResultSet rs = stmt.executeQuery("SELECT airline_id FROM airline_booking WHERE Customer_id = '" + custID + "'" ); //lw la2eet eno mwgood
//            if (rs != null) 
//            {
//                  ArilineGUI a = new ArilineGUI();
//                  a.setVisible(true);
//            }
//            else if( rs.next())
//            {
//                ResultSet rs1 = stmt.executeQuery("SELECT carid FROM carrental_booking WHERE custid = custID");
//                if(rs1!= null)
//                {
////                    CarRentalGUI c = new CarRentalGUI();
////                    c.setVisible(true);
//                }
//            }
//             else if( rs.next())
//            {
//                ResultSet rs2 = stmt.executeQuery("SELECT hotel_id FROM room_booking WHERE custid = custID");
//                if(rs2!= null)
//                {
////                    hotelGUI h = new hotelGUI();
////                    h.setVisible(true);
//                }
//            }
//        } catch (Exception e) {
//            System.err.println("DATABASE QUERY ERROR: " + e.toString());
//        }
//      
//      
//      }
//      
//      
//      
//      
//      
//      
      
      
      
      
      
//            try {
//            Statement stmt = con.createStatement();
//            ResultSet rs = stmt.executeQuery("select * from students where name = '" + name + "'");
//            if (rs.first()) {
//                return new Student(rs.getString("name"), rs.getDouble("gpa"));
//            }
//        } catch (Exception e) {
//            System.err.println("DATABASE QUERY ERROR: " + e.toString());
//        }
//        return null;
//            try {
//            Statement stmt = con.createStatement();
//            String sql = "SELECT * FROM Airline WHERE bookingID = airline_id ";  
//            ResultSet rs = stmt.executeQuery(sql);
//            while (rs.next()) {
//               String PlaneID =rs.getNString("Plane_id");
//               String DepartureDate=rs.getNString("DepartureDate_Time");
//               String ArrivalDate=rs.getNString("ArrivalDate");
//               String Booking_Status=rs.getNString("Booking_Status");
//               String Class=rs.getNString("Class");
//               String Seat_Number=rs.getNString("Seat_Number");
//               String Ticket_Price=rs.getNString("Ticket_Price");
//               String Flight_Number=rs.getNString("Flight_Number");
//                }
//            rs.close();
//            stmt.close();
//            con.close();
//            
//            
//            } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(null,"Connect failed ! " );
//        }
        
    
//        
//        else if(jCheckBox2.isSelected())
//        {
//              PaymentEditUI p= new PaymentEditUI();
//              p.setVisible(true);
//        }
//        else if (jCheckBox3.isSelected())
//        {
//            AddressEditUI a= new AddressEditUI();
//            a.setVisible(true);
//        }
//    
                                   
//    int reservation = jTextField1.getText();
//        if(id==0)
//        {
//            JOptionPane.showMessageDialog(this, "Please enter your ID");
//        }
//        else
//        {
//           try {
//            Statement stmt = con.createStatement();
//            ResultSet rs = stmt.executeQuery("select Booking_id FROM customer_booking where Customer_id = id");
//            if (rs.first()) {
//                ResultSet rs2 = stmt.executeQuery("select room_num from room_booking where bookingid = Booking_id"); 
//                  ResultSet rs3 = stmt.executeQuery("select carid from carrental_booking where bookingid = Booking_id");
//                    ResultSet rs4 = stmt.executeQuery("select airline_id from arline_booking where booking_id = Booking_id");
//                     ResultSet rs5 = stmt.executeQuery("select tourid from tour_booking where bookingid = Booking_id");
//                    if(rs2 != null)
//                    {
//                          ResultSet rs6 = stmt.executeQuery("select * from hotel where Hotel_ID = Booking_id");
//                    } 
//                    if(rs3 != null)
//                    {
//                          ResultSet rs6 = stmt.executeQuery("select * from car_rental where Car_id = Booking_id");
//                    }
//                     if(rs4 != null)
//                    {
//                          ResultSet rs6 = stmt.executeQuery("select * from airline where Plane_id = Booking_id");
//                    }
//                       if(rs5 != null)
//                    {
//                          ResultSet rs6 = stmt.executeQuery("select * from tour where Tour_id = Booking_id");
//                    }
//            }
//        } catch (Exception e) {
//            System.err.println("DATABASE QUERY ERROR: " + e.toString());
//        }
//            ArtistUI a = new ArtistUI();
//            a.setVisible(true);
         
           // TODO add your handling code here:
    }//GEN-LAST:event_NextActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Next;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
